name: flappy_bird_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  perfect_volume_control: ^1.0.5

  cupertino_icons: ^1.0.2
  flame: ^1.16.0
  flame_audio: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Game     
      fonts:
        - asset: assets/fonts/Game.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"